### ISSUE TITLE
Dev script not working

### ISSUE THREAD

**Issue by mickdekkers** [pi0/nuxt-starter-pwa#3]
Greetings, when trying to run `yarn dev` or `nuxt` directly, I'm getting these errors:

```
@nuxtjs/offline TypeError: Cannot read property 'offline' of undefined
    at nuxtOffline (C:\Projects\timato\frontend\node_modules\@nuxtjs\offline\index.js:40:34)
    at install (C:\Projects\timato\frontend\node_modules\nuxt-modules\index.js:127:12)
    at modules.forEach.module (C:\Projects\timato\frontend\node_modules\nuxt-modules\index.js:42:15)
    at Array.forEach (native)
    at wrap (C:\Projects\timato\frontend\node_modules\nuxt-modules\index.js:40:11)
    at Object.<anonymous> (C:\Projects\timato\frontend\nuxt.config.js:1:103)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Projects\timato\frontend\node_modules\nuxt\bin\nuxt-dev:35:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
@nuxtjs/manifest TypeError: Cannot read property 'manifest' of undefined
    at nuxtManifest (C:\Projects\timato\frontend\node_modules\@nuxtjs\manifest\index.js:8:39)
    at install (C:\Projects\timato\frontend\node_modules\nuxt-modules\index.js:127:12)
    at modules.forEach.module (C:\Projects\timato\frontend\node_modules\nuxt-modules\index.js:42:15)
    at Array.forEach (native)
    at wrap (C:\Projects\timato\frontend\node_modules\nuxt-modules\index.js:40:11)
    at Object.<anonymous> (C:\Projects\timato\frontend\nuxt.config.js:1:103)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Projects\timato\frontend\node_modules\nuxt\bin\nuxt-dev:35:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
[]
[nuxt] error while initializing modules
TypeError: Cannot read property 'postcss' of undefined
    at Module.module.exports (C:\Projects\timato\frontend\node_modules\@nuxtjs\optimize\index.js:17:13)
    at C:\Projects\timato\frontend\node_modules\nuxt\dist\nuxt.js:1646:29
    at F (C:\Projects\timato\frontend\node_modules\core-js\library\modules\_export.js:35:28)
    at Module.addModule (C:\Projects\timato\frontend\node_modules\nuxt\dist\nuxt.js:1645:14)
    at C:\Projects\timato\frontend\node_modules\nuxt\dist\nuxt.js:197:14
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
error Command failed with exit code 1.
```

If I had to guess, this is happening because all the dependencies are set to `latest` in the `package.json`, and a breaking change got introduced at some point.

---

Windows 10 64-bit

`yarn` 0.24.6
`vue-cli` 2.8.1

"latest" packages:
`nuxt` 1.0.0-alpha1
`nuxt-modules` 0.11.3
`@nuxtjs/manifest` 1.0.0
`@nuxtjs/offline` 1.0.0
`@nuxtjs/optimize` 1.0.0

**Comment by pi0** [comment]
Good day @SoullessWaffle . `1.x.x` tagged modules are now compatible with official nuxt.js modules integration system instead. We are heavily working to provide an official and stable PWA template soon. Until then it would be safe to keep with `0.x.x` modules.

**Comment by mickdekkers** [comment]
Hi @pi0, thanks for your reply. After locking the versions of the `@nuxt` modules to `<1.0.0` and reinstalling dependencies, I'm now getting a different error:

```
C:\Projects\timato\frontend>yarn dev
yarn dev v0.24.6
$ nuxt
[ { src: 'C:\\Projects\\timato\\frontend\\.nuxt-modules\\modules\\nuxt_offline_plugin.js',
    ssr: false } ]
[nuxt] error while initializing modules
TypeError: Cannot read property 'filenames' of undefined
    at Module.module.exports (C:\Projects\timato\frontend\node_modules\@nuxtjs\optimize\index.js:5:18)
    at C:\Projects\timato\frontend\node_modules\nuxt\dist\nuxt.js:1646:29
    at F (C:\Projects\timato\frontend\node_modules\core-js\library\modules\_export.js:35:28)
    at Module.addModule (C:\Projects\timato\frontend\node_modules\nuxt\dist\nuxt.js:1645:14)
    at C:\Projects\timato\frontend\node_modules\nuxt\dist\nuxt.js:197:14
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
error Command failed with exit code 1.
```

These are my dependencies:
```json
"dependencies": {
  "@nuxtjs/manifest": "<1.0.0",
  "@nuxtjs/offline": "<1.0.0",
  "@nuxtjs/optimize": "<1.0.0",
  "nuxt": "latest",
  "nuxt-modules": "latest"
}
```

Should I also lock `nuxt-modules` and/or `nuxt` to a specific version?

**Comment by pi0** [comment]
Your are using incompatible versions again :)) Nuxt should be downgraded  to `^0.10.7` . BTW suggest you just wait for new stable template instead of downgrading...

**Comment by mickdekkers** [comment]
Ah alright, I'll do that then. Thanks again! :)

**Comment by pi0** [comment]
New official PWA template: https://github.com/nuxt-community/pwa-template

BTW Thanks for all your helps making that happen!
